# Generated by Django 4.2.3 on 2023-07-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church_service',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='features',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='sermons',
            name='deleted',
        ),
    ]
